/**
 * lib/autofix/pr-creator.ts
 *
 * Creates a GitHub PR with the auto-fixed code.
 * Uses either the GitHub App installation token or a personal token.
 */

import { Octokit } from '@octokit/rest'

export interface CreateFixPRParams {
  octokit:      Octokit
  owner:        string
  repo:         string
  baseBranch:   string
  filePath:     string
  originalSha:  string   // blob SHA of the original file
  fixedContent: string
  prTitle:      string
  prBody:       string
}

export interface CreateFixPRResult {
  ok:     boolean
  prUrl?: string
  prNumber?: number
  branch?: string
  error?: string
}

export async function createFixPR(params: CreateFixPRParams): Promise<CreateFixPRResult> {
  const { octokit, owner, repo, baseBranch, filePath, originalSha, fixedContent, prTitle, prBody } = params

  try {
    // 1. Get base branch SHA
    const { data: ref } = await octokit.request('GET /repos/{owner}/{repo}/git/ref/{ref}', {
      owner, repo, ref: `heads/${baseBranch}`,
    })
    const baseSha = ref.object.sha

    // 2. Create new branch
    const branchName = `breakshield/autofix-${Date.now()}`
    await octokit.request('POST /repos/{owner}/{repo}/git/refs', {
      owner, repo,
      ref: `refs/heads/${branchName}`,
      sha: baseSha,
    })

    // 3. Create blob with fixed content
    const { data: blob } = await octokit.request('POST /repos/{owner}/{repo}/git/blobs', {
      owner, repo,
      content: Buffer.from(fixedContent).toString('base64'),
      encoding: 'base64',
    })

    // 4. Get base tree
    const { data: commit } = await octokit.request('GET /repos/{owner}/{repo}/git/commits/{commit_sha}', {
      owner, repo, commit_sha: baseSha,
    })

    // 5. Create new tree with fixed file
    const { data: tree } = await octokit.request('POST /repos/{owner}/{repo}/git/trees', {
      owner, repo,
      base_tree: commit.tree.sha,
      tree: [{
        path: filePath,
        mode: '100644',
        type: 'blob',
        sha: blob.sha,
      }],
    })

    // 6. Create commit
    const { data: newCommit } = await octokit.request('POST /repos/{owner}/{repo}/git/commits', {
      owner, repo,
      message: `fix: auto-fix breaking change in ${filePath}\n\nGenerated by BreakShield CI`,
      tree: tree.sha,
      parents: [baseSha],
    })

    // 7. Update branch to point to new commit
    await octokit.request('PATCH /repos/{owner}/{repo}/git/refs/{ref}', {
      owner, repo,
      ref: `heads/${branchName}`,
      sha: newCommit.sha,
    })

    // 8. Create PR
    const { data: pr } = await octokit.request('POST /repos/{owner}/{repo}/pulls', {
      owner, repo,
      title: prTitle,
      body:  prBody,
      head:  branchName,
      base:  baseBranch,
    })

    return {
      ok: true,
      prUrl: pr.html_url,
      prNumber: pr.number,
      branch: branchName,
    }
  } catch (e: any) {
    return { ok: false, error: e.message ?? String(e) }
  }
}
