/**
 * app/api/autofix/route.ts
 *
 * Generates an AI fix for a breaking change and creates a GitHub PR.
 *
 * POST /api/autofix
 * Body: {
 *   owner, repo, baseBranch, prNumber,
 *   filePath, headSha,
 *   finding: { changeType, affectedValue, description, beforeSchema?, afterSchema? },
 *   userGeminiKey?: string   // BYOK
 * }
 */

import { NextRequest, NextResponse } from 'next/server'
import { Octokit } from '@octokit/rest'
import { getSession } from '@/lib/auth'
import { getInstallationOctokit } from '@/lib/github/client'
import { generateFix } from '@/lib/autofix/gemini'
import { createFixPR } from '@/lib/autofix/pr-creator'

// ─── Fetch file content at a specific ref ─────────────────────────────────────

async function fetchFile(octokit: Octokit, owner: string, repo: string, path: string, ref: string) {
  try {
    const { data } = await octokit.request('GET /repos/{owner}/{repo}/contents/{path}', {
      owner, repo, path, ref,
    }) as any
    if (data.content && data.encoding === 'base64') {
      return {
        content: Buffer.from(data.content.replace(/\n/g, ''), 'base64').toString('utf-8'),
        sha: data.sha as string,
      }
    }
    return null
  } catch {
    return null
  }
}

// ─── Route handler ────────────────────────────────────────────────────────────

export async function POST(req: NextRequest): Promise<NextResponse> {
  const session = await getSession(req)
  if (!session) {
    return NextResponse.json({ error: 'Sign in to use auto-fix' }, { status: 401 })
  }

  let body: any
  try { body = await req.json() } catch { return NextResponse.json({ error: 'Invalid JSON' }, { status: 400 }) }

  const {
    owner, repo, baseBranch, prNumber,
    filePath, headSha,
    finding,
    installationId,
    userGeminiKey,
  } = body

  if (!owner || !repo || !filePath || !finding) {
    return NextResponse.json({ error: 'Missing required fields' }, { status: 400 })
  }

  // ── Get Octokit ──────────────────────────────────────────────────────────
  let octokit: Octokit
  if (installationId) {
    try {
      octokit = await getInstallationOctokit(installationId) as unknown as Octokit
    } catch {
      octokit = new Octokit({ auth: session.accessToken })
    }
  } else {
    octokit = new Octokit({ auth: session.accessToken })
  }

  // ── Fetch the file to fix ────────────────────────────────────────────────
  // Use headSha if provided, otherwise fall back to baseBranch HEAD
  const ref = headSha || baseBranch || 'HEAD'
  const file = await fetchFile(octokit, owner, repo, filePath, ref)
  if (!file) {
    return NextResponse.json({ error: `Could not fetch file: ${filePath}` }, { status: 400 })
  }

  // ── Generate fix with Gemini ─────────────────────────────────────────────
  const fixResult = await generateFix({
    filePath,
    fileContent:   file.content,
    changeType:    finding.changeType,
    affectedValue: finding.affectedValue,
    description:   finding.description,
    beforeSchema:  finding.beforeSchema,
    afterSchema:   finding.afterSchema,
    userApiKey:    userGeminiKey,
  })

  if (!fixResult.ok || !fixResult.fixedCode) {
    return NextResponse.json({ error: fixResult.error ?? 'Fix generation failed' }, { status: 500 })
  }

  // Don't create PR if content is unchanged
  if (fixResult.fixedCode.trim() === file.content.trim()) {
    return NextResponse.json({
      error: 'Could not generate a fix automatically. The change may require manual intervention.',
    }, { status: 422 })
  }

  // ── Create PR with fix ───────────────────────────────────────────────────
  const prBody = `## BreakShield CI — Auto-fix

This PR was automatically generated to fix a breaking API change detected in PR #${prNumber ?? '?'}.

### What was fixed
| | |
|:--|:--|
| **File** | \`${filePath}\` |
| **Change** | ${finding.changeType.replace(/_/g, ' ')} |
| **Affected** | \`${finding.affectedValue}\` |
| **Description** | ${finding.description} |
${finding.beforeSchema ? `| **Before** | \`${finding.beforeSchema}\` |` : ''}
${finding.afterSchema  ? `| **After** | \`${finding.afterSchema}\` |` : ''}

### How to use
1. Review the changes in this PR
2. If the fix looks correct, click **Merge**
3. If not, close this PR and fix manually

---
*Generated by [BreakShield CI](https://breakshield-ci.vercel.app) using Google Gemini*`

  const prTitle = `fix: [BreakShield] auto-fix ${finding.changeType.replace(/_/g, ' ')} in ${filePath.split('/').pop()}`

  const prResult = await createFixPR({
    octokit,
    owner, repo,
    baseBranch: baseBranch ?? 'main',
    filePath,
    originalSha: file.sha,
    fixedContent: fixResult.fixedCode,
    prTitle,
    prBody,
  })

  if (!prResult.ok) {
    return NextResponse.json({ error: prResult.error ?? 'PR creation failed' }, { status: 500 })
  }

  return NextResponse.json({
    ok: true,
    prUrl: prResult.prUrl,
    prNumber: prResult.prNumber,
    branch: prResult.branch,
  })
}
